language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
  - npm install -g expo-cli
jobs:
  include:
    - stage: 'Testing App'
      node_js: lts/*
      script:
        - npm ci
        - npx jest --ci
    - stage: 'Release to Staging Build'
      node_js: lts/*
      script:
        - npm ci
        - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - yes | expo build:android --release-channel staging --no-publish --no-wait --non-interactive